services:
  bun-server:
    build: .                       # Build from the Dockerfile in the current directory
    container_name: bun_hono_server
    environment:
      - NODE_ENV=development 
    # volumes:
    #   - ./:/app                    # Mounts your local app directory to /app in the container
    ports:
      - "3000:3000"                # Exposes port 3000 (adjust if needed)
    depends_on:
      db:
        condition: service_healthy
    restart: always
    develop:
      watch:
        - action: rebuild
          path: ./server
        - action: rebuild
          path: package.json
        - action: rebuild
          path: ./dist

  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=video-proc
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d video-proc -U user"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  postgres-data:
